### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by rwjblue** [mike-north/qunit-metadata#1]
This looks really neat! The README does a great job of explaining "how" to use the library, but doesn't seem to touch at all on "why" you would...

Maybe there is room for a small motivating example showing how it is useful to have additional metadata?

**Comment by mike-north** [comment]
It'll be easier to add this once I reach my first use case and can illustrate with a screenshot: assigning points and achievements to tests for workshop gamification purposes.

**Comment by rwjblue** [comment]
Seems neat for sure! I only opened the issue because after I read the README I was left with a good understanding of what the library does and how I could use it, but no clue why or when to use it....
